version: '3'
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  fluentd:
    image: ${USER_NAME}/fluentd:latest
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - back_net
      - front_net

  elasticsearch:
    image: elasticsearch:5.6.11-alpine
    ports:
      - "9200:9200"
    networks:
      - back_net
      - front_net

  kibana:
    image: kibana:5.6.12
    ports:
      - "5601:5601"
    networks:
      - back_net
      - front_net
networks:
  back_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
  front_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
