version: '3'
services:
  fluentd:
    image: ${USER_NAME}/fluentd:latest
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:5.6.11-alpine
    ports:
      - "9200:9200"

  kibana:
    image: kibana:5.6.12
    ports:
      - "5601:5601"
