version: '3.3'
services:
  post_db:
    image: mongo:3.2
    env_file: .env
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    env_file: .env
    ports:
      - ${TCP_PORT}:${TCP_PORT}/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    env_file: .env
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    env_file: .env
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  reddit:
